from solutions.day08.part1 import solve_part1
from solutions.day08.part2 import solve_part2


TEST_INPUT = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""


def test_part1():
    assert solve_part1(TEST_INPUT.strip()) == 14


def test_part2():
    assert solve_part2(TEST_INPUT.strip()) == 34
